

CREATE TABLE Cliente (
    BALCAO VARCHAR,
    E_MAIL VARCHAR,
    NOME_CLI VARCHAR,
    DATA_NASC DATE,
    CPF CHAR,
    SEXO VARCHAR,
    TELEFONE CHAR,
    ID_CLIENTE INTEGER PRIMARY KEY,
    CNPJ CHAR,
    UNIQUE (E_MAIL, CNPJ)
);

CREATE TABLE Funcionario (
    CNPJ CHAR,
    NOME VARCHAR,
    DATA_NASC DATE,
    RG CHAR,
    CARGO VARCHAR,
    E_MAIL VARCHAR,
    SEXO INTEGER,
    ENDERECO VARCHAR,
    TELEFONE CHAR,
    ID_FUNCIONARIO INTEGER PRIMARY KEY,
    UNIQUE (CNPJ, E_MAIL)
);

CREATE TABLE Fornecedor (
    NOME VARCHAR,
    CNPJ CHAR,
    E_MAIL VARCHAR,
    TEL INTEGER,
    ID_FORNECEDOR INTEGER PRIMARY KEY,
    UNIQUE (E_MAIL, CNPJ)
);

CREATE TABLE Produto (
    ID_PROD INTEGER PRIMARY KEY,
    VALIDADE DATE,
    CUSTO FLOAT,
    PRECO_VENDA FLOAT,
    CNPJ_FORN CHAR UNIQUE
);

CREATE TABLE Pedido (
    ID_PEDIDO INTEGER PRIMARY KEY,
    DATA DATE,
    VALOR_TOTAL FLOAT,
    COD_FLOR INTEGER,
    COD_PRODUTO INTEGER,
    CNPJ_FUNC CHAR UNIQUE
);

CREATE TABLE Flor (
    ID_FLOR INTEGER PRIMARY KEY,
    COR VARCHAR,
    ESPECIE VARCHAR,
    CNPJ_FORN CHAR,
    CUSTO FLOAT,
    PRECO_VENDA FLOAT
);

CREATE TABLE Fornece_Produto_Fornecedor_Flor (
    fk_Produto_ID_PROD INTEGER,
    fk_Fornecedor_ID_FORNECEDOR INTEGER,
    fk_Flor_ID_FLOR INTEGER
);

CREATE TABLE Contem_Produto_Flor_Pedido (
    fk_Produto_ID_PROD INTEGER,
    fk_Flor_ID_FLOR INTEGER,
    fk_Pedido_ID_PEDIDO INTEGER
);

CREATE TABLE Realiza (
    fk_Pedido_ID_PEDIDO INTEGER,
    fk_Funcionario_ID_FUNCIONARIO INTEGER
);

CREATE TABLE Realiza (
    fk_Pedido_ID_PEDIDO INTEGER,
    fk_Cliente_ID_CLIENTE INTEGER
);
 
ALTER TABLE Fornece_Produto_Fornecedor_Flor ADD CONSTRAINT FK_Fornece_Produto_Fornecedor_Flor_1
    FOREIGN KEY (fk_Produto_ID_PROD)
    REFERENCES Produto (ID_PROD)
    ON DELETE NO ACTION;
 
ALTER TABLE Fornece_Produto_Fornecedor_Flor ADD CONSTRAINT FK_Fornece_Produto_Fornecedor_Flor_2
    FOREIGN KEY (fk_Fornecedor_ID_FORNECEDOR)
    REFERENCES Fornecedor (ID_FORNECEDOR)
    ON DELETE NO ACTION;
 
ALTER TABLE Fornece_Produto_Fornecedor_Flor ADD CONSTRAINT FK_Fornece_Produto_Fornecedor_Flor_3
    FOREIGN KEY (fk_Flor_ID_FLOR)
    REFERENCES Flor (ID_FLOR)
    ON DELETE NO ACTION;
 
ALTER TABLE Contem_Produto_Flor_Pedido ADD CONSTRAINT FK_Contem_Produto_Flor_Pedido_1
    FOREIGN KEY (fk_Produto_ID_PROD)
    REFERENCES Produto (ID_PROD)
    ON DELETE NO ACTION;
 
ALTER TABLE Contem_Produto_Flor_Pedido ADD CONSTRAINT FK_Contem_Produto_Flor_Pedido_2
    FOREIGN KEY (fk_Flor_ID_FLOR)
    REFERENCES Flor (ID_FLOR)
    ON DELETE NO ACTION;
 
ALTER TABLE Contem_Produto_Flor_Pedido ADD CONSTRAINT FK_Contem_Produto_Flor_Pedido_3
    FOREIGN KEY (fk_Pedido_ID_PEDIDO)
    REFERENCES Pedido (ID_PEDIDO)
    ON DELETE NO ACTION;
 
ALTER TABLE Realiza ADD CONSTRAINT FK_Realiza_1
    FOREIGN KEY (fk_Pedido_ID_PEDIDO)
    REFERENCES Pedido (ID_PEDIDO)
    ON DELETE RESTRICT;
 
ALTER TABLE Realiza ADD CONSTRAINT FK_Realiza_2
    FOREIGN KEY (fk_Funcionario_ID_FUNCIONARIO)
    REFERENCES Funcionario (ID_FUNCIONARIO)
    ON DELETE RESTRICT;
 
ALTER TABLE Realiza ADD CONSTRAINT FK_Realiza_1
    FOREIGN KEY (fk_Pedido_ID_PEDIDO)
    REFERENCES Pedido (ID_PEDIDO)
    ON DELETE RESTRICT;
 
ALTER TABLE Realiza ADD CONSTRAINT FK_Realiza_2
    FOREIGN KEY (fk_Cliente_ID_CLIENTE)
    REFERENCES Cliente (ID_CLIENTE)
    ON DELETE RESTRICT;